version: '3.8'

services:
  usuarios-service:
    build:
      context: ./usuarios-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - LISTEN_PORT=8001

  produtos-service:
    build:
      context: ./produtos-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - LISTEN_PORT=8002
      - USER_SERVICE_URL=http://usuarios-service
      - USER_SERVICE_PORT=8001
    depends_on:
      - usuarios-service
    